# Generated by Django 5.0.6 on 2024-06-29 12:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=250)),
                ('url', models.SlugField(max_length=250)),
                ('Cuerpo', models.TextField()),
                ('publicación', models.DateTimeField(default=django.utils.timezone.now)),
                ('creación', models.DateTimeField(auto_now_add=True)),
                ('actualización', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
