# Generated by Django 5.0.6 on 2024-06-29 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publish']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='creación',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='publicación',
            new_name='publish',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='actualización',
            new_name='update',
        ),
    ]
