# Generated by Django 5.0.6 on 2024-07-01 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_author'),
    ]

    operations = [
    ]
