# Generated by Django 5.0.6 on 2024-06-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_blog_post_publish_bb7600_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Titulo',
            field=models.CharField(max_length=250, verbose_name='Titulo'),
        ),
    ]
