# Generated by Django 5.0.6 on 2024-07-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Cuerpo',
        ),
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default='', verbose_name='Cuerpo'),
        ),
    ]
