# Generated by Django 5.0.6 on 2024-07-01 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='Cuerpo',
        ),
    ]
