# Generated by Django 5.0.6 on 2024-07-03 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_body_post_cuerpo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Cuerpo',
            new_name='body',
        ),
    ]
