# Generated by Django 5.0.6 on 2024-06-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='perfil.jpg', null=True, upload_to='fotos_perfil/'),
        ),
    ]
